<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data From https://www.countrycode.org

        $seedCountries = [
            ['name' => 'Afghanistan', 'dial_code' => '93', 'iso2' => 'AF', 'iso3' => 'AFG',],
            ['name' => 'Albania', 'dial_code' => '355 ', 'iso2' => 'AL', 'iso3' => 'ALB',],
            ['name' => 'Algeria', 'dial_code' => '213 ', 'iso2' => 'DZ', 'iso3' => 'DZA',],
            ['name' => 'American Samoa ', 'dial_code' => '1-684 ', 'iso2' => 'AS', 'iso3' => 'ASM',],
            ['name' => 'Andorra', 'dial_code' => '376 ', 'iso2' => 'AD', 'iso3' => 'AND',],
            ['name' => 'Angola ', 'dial_code' => '244 ', 'iso2' => 'AO', 'iso3' => 'AGO',],
            ['name' => 'Anguilla ', 'dial_code' => '1-264 ', 'iso2' => 'AI', 'iso3' => 'AIA',],
            ['name' => 'Antarctica ', 'dial_code' => '672 ', 'iso2' => 'AQ', 'iso3' => 'ATA',],
            ['name' => 'Antigua and Barbuda', 'dial_code' => '1-268 ', 'iso2' => 'AG', 'iso3' => 'ATG',],
            ['name' => 'Argentina', 'dial_code' => '54', 'iso2' => 'AR', 'iso3' => 'ARG',],
            ['name' => 'Armenia', 'dial_code' => '374 ', 'iso2' => 'AM', 'iso3' => 'ARM',],
            ['name' => 'Aruba', 'dial_code' => '297 ', 'iso2' => 'AW', 'iso3' => 'ABW',],
            ['name' => 'Australia', 'dial_code' => '61', 'iso2' => 'AU', 'iso3' => 'AUS',],
            ['name' => 'Austria', 'dial_code' => '43', 'iso2' => 'AT', 'iso3' => 'AUT',],
            ['name' => 'Azerbaijan ', 'dial_code' => '994 ', 'iso2' => 'AZ', 'iso3' => 'AZE',],
            ['name' => 'Bahamas', 'dial_code' => '1-242 ', 'iso2' => 'BS', 'iso3' => 'BHS',],
            ['name' => 'Bahrain', 'dial_code' => '973 ', 'iso2' => 'BH', 'iso3' => 'BHR',],
            ['name' => 'Bangladesh ', 'dial_code' => '880 ', 'iso2' => 'BD', 'iso3' => 'BGD',],
            ['name' => 'Barbados ', 'dial_code' => '1-246 ', 'iso2' => 'BB', 'iso3' => 'BRB',],
            ['name' => 'Belarus', 'dial_code' => '375 ', 'iso2' => 'BY', 'iso3' => 'BLR',],
            ['name' => 'Belgium', 'dial_code' => '32', 'iso2' => 'BE', 'iso3' => 'BEL',],
            ['name' => 'Belize ', 'dial_code' => '501 ', 'iso2' => 'BZ', 'iso3' => 'BLZ',],
            ['name' => 'Benin', 'dial_code' => '229 ', 'iso2' => 'BJ', 'iso3' => 'BEN',],
            ['name' => 'Bermuda', 'dial_code' => '1-441 ', 'iso2' => 'BM', 'iso3' => 'BMU',],
            ['name' => 'Bhutan ', 'dial_code' => '975 ', 'iso2' => 'BT', 'iso3' => 'BTN',],
            ['name' => 'Bolivia', 'dial_code' => '591 ', 'iso2' => 'BO', 'iso3' => 'BOL',],
            ['name' => 'Bosnia and Herzegovina ', 'dial_code' => '387 ', 'iso2' => 'BA', 'iso3' => 'BIH',],
            ['name' => 'Botswana ', 'dial_code' => '267 ', 'iso2' => 'BW', 'iso3' => 'BWA',],
            ['name' => 'Brazil ', 'dial_code' => '55', 'iso2' => 'BR', 'iso3' => 'BRA',],
            ['name' => 'British Indian Ocean Territory ', 'dial_code' => '246 ', 'iso2' => 'IO', 'iso3' => 'IOT',],
            ['name' => 'British Virgin Islands ', 'dial_code' => '1-284 ', 'iso2' => 'VG', 'iso3' => 'VGB',],
            ['name' => 'Brunei ', 'dial_code' => '673 ', 'iso2' => 'BN', 'iso3' => 'BRN',],
            ['name' => 'Bulgaria ', 'dial_code' => '359 ', 'iso2' => 'BG', 'iso3' => 'BGR',],
            ['name' => 'Burkina Faso ', 'dial_code' => '226 ', 'iso2' => 'BF', 'iso3' => 'BFA',],
            ['name' => 'Burundi', 'dial_code' => '257 ', 'iso2' => 'BI', 'iso3' => 'BDI',],
            ['name' => 'Cambodia ', 'dial_code' => '855 ', 'iso2' => 'KH', 'iso3' => 'KHM',],
            ['name' => 'Cameroon ', 'dial_code' => '237 ', 'iso2' => 'CM', 'iso3' => 'CMR',],
            ['name' => 'Canada ', 'dial_code' => '1 ', 'iso2' => 'CA', 'iso3' => 'CAN',],
            ['name' => 'Cape Verde ', 'dial_code' => '238 ', 'iso2' => 'CV', 'iso3' => 'CPV',],
            ['name' => 'Cayman Islands ', 'dial_code' => '1-345 ', 'iso2' => 'KY', 'iso3' => 'CYM',],
            ['name' => 'Central African Republic ', 'dial_code' => '236 ', 'iso2' => 'CF', 'iso3' => 'CAF',],
            ['name' => 'Chad ', 'dial_code' => '235 ', 'iso2' => 'TD', 'iso3' => 'TCD',],
            ['name' => 'Chile', 'dial_code' => '56', 'iso2' => 'CL', 'iso3' => 'CHL',],
            ['name' => 'China', 'dial_code' => '86', 'iso2' => 'CN', 'iso3' => 'CHN',],
            ['name' => 'Christmas Island ', 'dial_code' => '61', 'iso2' => 'CX', 'iso3' => 'CXR',],
            ['name' => 'Cocos Islands', 'dial_code' => '61', 'iso2' => 'CC', 'iso3' => 'CCK',],
            ['name' => 'Colombia ', 'dial_code' => '57', 'iso2' => 'CO', 'iso3' => 'COL',],
            ['name' => 'Comoros', 'dial_code' => '269 ', 'iso2' => 'KM', 'iso3' => 'COM',],
            ['name' => 'Cook Islands ', 'dial_code' => '682 ', 'iso2' => 'CK', 'iso3' => 'COK',],
            ['name' => 'Costa Rica ', 'dial_code' => '506 ', 'iso2' => 'CR', 'iso3' => 'CRI',],
            ['name' => 'Croatia', 'dial_code' => '385 ', 'iso2' => 'HR', 'iso3' => 'HRV',],
            ['name' => 'Cuba ', 'dial_code' => '53', 'iso2' => 'CU', 'iso3' => 'CUB',],
            ['name' => 'Curacao', 'dial_code' => '599 ', 'iso2' => 'CW', 'iso3' => 'CUW',],
            ['name' => 'Cyprus ', 'dial_code' => '357 ', 'iso2' => 'CY', 'iso3' => 'CYP',],
            ['name' => 'Czech Republic ', 'dial_code' => '420 ', 'iso2' => 'CZ', 'iso3' => 'CZE',],
            ['name' => 'Democratic Republic of the Congo ', 'dial_code' => '243 ', 'iso2' => 'CD', 'iso3' => 'COD',],
            ['name' => 'Denmark', 'dial_code' => '45', 'iso2' => 'DK', 'iso3' => 'DNK',],
            ['name' => 'Djibouti ', 'dial_code' => '253 ', 'iso2' => 'DJ', 'iso3' => 'DJI',],
            ['name' => 'Dominica ', 'dial_code' => '1-767 ', 'iso2' => 'DM', 'iso3' => 'DMA',],
            ['name' => 'Dominican Republic ', 'dial_code' => '1-809, 1-829, 1-849 ', 'iso2' => 'DO', 'iso3' => 'DOM',],
            ['name' => 'East Timor ', 'dial_code' => '670 ', 'iso2' => 'TL', 'iso3' => 'TLS',],
            ['name' => 'Ecuador', 'dial_code' => '593 ', 'iso2' => 'EC', 'iso3' => 'ECU',],
            ['name' => 'Egypt', 'dial_code' => '20', 'iso2' => 'EG', 'iso3' => 'EGY',],
            ['name' => 'El Salvador', 'dial_code' => '503 ', 'iso2' => 'SV', 'iso3' => 'SLV',],
            ['name' => 'Equatorial Guinea', 'dial_code' => '240 ', 'iso2' => 'GQ', 'iso3' => 'GNQ',],
            ['name' => 'Eritrea', 'dial_code' => '291 ', 'iso2' => 'ER', 'iso3' => 'ERI',],
            ['name' => 'Estonia', 'dial_code' => '372 ', 'iso2' => 'EE', 'iso3' => 'EST',],
            ['name' => 'Ethiopia ', 'dial_code' => '251 ', 'iso2' => 'ET', 'iso3' => 'ETH',],
            ['name' => 'Falkland Islands ', 'dial_code' => '500 ', 'iso2' => 'FK', 'iso3' => 'FLK',],
            ['name' => 'Faroe Islands', 'dial_code' => '298 ', 'iso2' => 'FO', 'iso3' => 'FRO',],
            ['name' => 'Fiji ', 'dial_code' => '679 ', 'iso2' => 'FJ', 'iso3' => 'FJI',],
            ['name' => 'Finland', 'dial_code' => '358 ', 'iso2' => 'FI', 'iso3' => 'FIN',],
            ['name' => 'France ', 'dial_code' => '33', 'iso2' => 'FR', 'iso3' => 'FRA',],
            ['name' => 'French Polynesia ', 'dial_code' => '689 ', 'iso2' => 'PF', 'iso3' => 'PYF',],
            ['name' => 'Gabon', 'dial_code' => '241 ', 'iso2' => 'GA', 'iso3' => 'GAB',],
            ['name' => 'Gambia ', 'dial_code' => '220 ', 'iso2' => 'GM', 'iso3' => 'GMB',],
            ['name' => 'Georgia', 'dial_code' => '995 ', 'iso2' => 'GE', 'iso3' => 'GEO',],
            ['name' => 'Germany', 'dial_code' => '49', 'iso2' => 'DE', 'iso3' => 'DEU',],
            ['name' => 'Ghana', 'dial_code' => '233 ', 'iso2' => 'GH', 'iso3' => 'GHA',],
            ['name' => 'Gibraltar', 'dial_code' => '350 ', 'iso2' => 'GI', 'iso3' => 'GIB',],
            ['name' => 'Greece ', 'dial_code' => '30', 'iso2' => 'GR', 'iso3' => 'GRC',],
            ['name' => 'Greenland', 'dial_code' => '299 ', 'iso2' => 'GL', 'iso3' => 'GRL',],
            ['name' => 'Grenada', 'dial_code' => '1-473 ', 'iso2' => 'GD', 'iso3' => 'GRD',],
            ['name' => 'Guam ', 'dial_code' => '1-671 ', 'iso2' => 'GU', 'iso3' => 'GUM',],
            ['name' => 'Guatemala', 'dial_code' => '502 ', 'iso2' => 'GT', 'iso3' => 'GTM',],
            ['name' => 'Guernsey ', 'dial_code' => '44-1481 ', 'iso2' => 'GG', 'iso3' => 'GGY',],
            ['name' => 'Guinea ', 'dial_code' => '224 ', 'iso2' => 'GN', 'iso3' => 'GIN',],
            ['name' => 'Guinea-Bissau', 'dial_code' => '245 ', 'iso2' => 'GW', 'iso3' => 'GNB',],
            ['name' => 'Guyana ', 'dial_code' => '592 ', 'iso2' => 'GY', 'iso3' => 'GUY',],
            ['name' => 'Haiti', 'dial_code' => '509 ', 'iso2' => 'HT', 'iso3' => 'HTI',],
            ['name' => 'Honduras ', 'dial_code' => '504 ', 'iso2' => 'HN', 'iso3' => 'HND',],
            ['name' => 'Hong Kong', 'dial_code' => '852 ', 'iso2' => 'HK', 'iso3' => 'HKG',],
            ['name' => 'Hungary', 'dial_code' => '36', 'iso2' => 'HU', 'iso3' => 'HUN',],
            ['name' => 'Iceland', 'dial_code' => '354 ', 'iso2' => 'IS', 'iso3' => 'ISL',],
            ['name' => 'India', 'dial_code' => '91', 'iso2' => 'IN', 'iso3' => 'IND',],
            ['name' => 'Indonesia', 'dial_code' => '62', 'iso2' => 'ID', 'iso3' => 'IDN',],
            ['name' => 'Iran ', 'dial_code' => '98', 'iso2' => 'IR', 'iso3' => 'IRN',],
            ['name' => 'Iraq ', 'dial_code' => '964 ', 'iso2' => 'IQ', 'iso3' => 'IRQ',],
            ['name' => 'Ireland', 'dial_code' => '353 ', 'iso2' => 'IE', 'iso3' => 'IRL',],
            ['name' => 'Isle of Man', 'dial_code' => '44-1624 ', 'iso2' => 'IM', 'iso3' => 'IMN',],
            ['name' => 'Israel ', 'dial_code' => '972 ', 'iso2' => 'IL', 'iso3' => 'ISR',],
            ['name' => 'Italy', 'dial_code' => '39', 'iso2' => 'IT', 'iso3' => 'ITA',],
            ['name' => 'Ivory Coast', 'dial_code' => '225 ', 'iso2' => 'CI', 'iso3' => 'CIV',],
            ['name' => 'Jamaica', 'dial_code' => '1-876 ', 'iso2' => 'JM', 'iso3' => 'JAM',],
            ['name' => 'Japan', 'dial_code' => '81', 'iso2' => 'JP', 'iso3' => 'JPN',],
            ['name' => 'Jersey ', 'dial_code' => '44-1534 ', 'iso2' => 'JE', 'iso3' => 'JEY',],
            ['name' => 'Jordan ', 'dial_code' => '962 ', 'iso2' => 'JO', 'iso3' => 'JOR',],
            ['name' => 'Kazakhstan ', 'dial_code' => '7 ', 'iso2' => 'KZ', 'iso3' => 'KAZ',],
            ['name' => 'Kenya', 'dial_code' => '254 ', 'iso2' => 'KE', 'iso3' => 'KEN',],
            ['name' => 'Kiribati ', 'dial_code' => '686 ', 'iso2' => 'KI', 'iso3' => 'KIR',],
            ['name' => 'Kosovo ', 'dial_code' => '383 ', 'iso2' => 'XK', 'iso3' => 'XKX',],
            ['name' => 'Kuwait ', 'dial_code' => '965 ', 'iso2' => 'KW', 'iso3' => 'KWT',],
            ['name' => 'Kyrgyzstan ', 'dial_code' => '996 ', 'iso2' => 'KG', 'iso3' => 'KGZ',],
            ['name' => 'Laos ', 'dial_code' => '856 ', 'iso2' => 'LA', 'iso3' => 'LAO',],
            ['name' => 'Latvia ', 'dial_code' => '371 ', 'iso2' => 'LV', 'iso3' => 'LVA',],
            ['name' => 'Lebanon', 'dial_code' => '961 ', 'iso2' => 'LB', 'iso3' => 'LBN',],
            ['name' => 'Lesotho', 'dial_code' => '266 ', 'iso2' => 'LS', 'iso3' => 'LSO',],
            ['name' => 'Liberia', 'dial_code' => '231 ', 'iso2' => 'LR', 'iso3' => 'LBR',],
            ['name' => 'Libya', 'dial_code' => '218 ', 'iso2' => 'LY', 'iso3' => 'LBY',],
            ['name' => 'Liechtenstein', 'dial_code' => '423 ', 'iso2' => 'LI', 'iso3' => 'LIE',],
            ['name' => 'Lithuania', 'dial_code' => '370 ', 'iso2' => 'LT', 'iso3' => 'LTU',],
            ['name' => 'Luxembourg ', 'dial_code' => '352 ', 'iso2' => 'LU', 'iso3' => 'LUX',],
            ['name' => 'Macau', 'dial_code' => '853 ', 'iso2' => 'MO', 'iso3' => 'MAC',],
            ['name' => 'Macedonia', 'dial_code' => '389 ', 'iso2' => 'MK', 'iso3' => 'MKD',],
            ['name' => 'Madagascar ', 'dial_code' => '261 ', 'iso2' => 'MG', 'iso3' => 'MDG',],
            ['name' => 'Malawi ', 'dial_code' => '265 ', 'iso2' => 'MW', 'iso3' => 'MWI',],
            ['name' => 'Malaysia ', 'dial_code' => '60', 'iso2' => 'MY', 'iso3' => 'MYS',],
            ['name' => 'Maldives ', 'dial_code' => '960 ', 'iso2' => 'MV', 'iso3' => 'MDV',],
            ['name' => 'Mali ', 'dial_code' => '223 ', 'iso2' => 'ML', 'iso3' => 'MLI',],
            ['name' => 'Malta', 'dial_code' => '356 ', 'iso2' => 'MT', 'iso3' => 'MLT',],
            ['name' => 'Marshall Islands ', 'dial_code' => '692 ', 'iso2' => 'MH', 'iso3' => 'MHL',],
            ['name' => 'Mauritania ', 'dial_code' => '222 ', 'iso2' => 'MR', 'iso3' => 'MRT',],
            ['name' => 'Mauritius', 'dial_code' => '230 ', 'iso2' => 'MU', 'iso3' => 'MUS',],
            ['name' => 'Mayotte', 'dial_code' => '262 ', 'iso2' => 'YT', 'iso3' => 'MYT',],
            ['name' => 'Mexico ', 'dial_code' => '52', 'iso2' => 'MX', 'iso3' => 'MEX',],
            ['name' => 'Micronesia ', 'dial_code' => '691 ', 'iso2' => 'FM', 'iso3' => 'FSM',],
            ['name' => 'Moldova', 'dial_code' => '373 ', 'iso2' => 'MD', 'iso3' => 'MDA',],
            ['name' => 'Monaco ', 'dial_code' => '377 ', 'iso2' => 'MC', 'iso3' => 'MCO',],
            ['name' => 'Mongolia ', 'dial_code' => '976 ', 'iso2' => 'MN', 'iso3' => 'MNG',],
            ['name' => 'Montenegro ', 'dial_code' => '382 ', 'iso2' => 'ME', 'iso3' => 'MNE',],
            ['name' => 'Montserrat ', 'dial_code' => '1-664 ', 'iso2' => 'MS', 'iso3' => 'MSR',],
            ['name' => 'Morocco', 'dial_code' => '212 ', 'iso2' => 'MA', 'iso3' => 'MAR',],
            ['name' => 'Mozambique ', 'dial_code' => '258 ', 'iso2' => 'MZ', 'iso3' => 'MOZ',],
            ['name' => 'Myanmar', 'dial_code' => '95', 'iso2' => 'MM', 'iso3' => 'MMR',],
            ['name' => 'Namibia', 'dial_code' => '264 ', 'iso2' => 'NA', 'iso3' => 'NAM',],
            ['name' => 'Nauru', 'dial_code' => '674 ', 'iso2' => 'NR', 'iso3' => 'NRU',],
            ['name' => 'Nepal', 'dial_code' => '977 ', 'iso2' => 'NP', 'iso3' => 'NPL',],
            ['name' => 'Netherlands', 'dial_code' => '31', 'iso2' => 'NL', 'iso3' => 'NLD',],
            ['name' => 'Netherlands Antilles ', 'dial_code' => '599 ', 'iso2' => 'AN', 'iso3' => 'ANT',],
            ['name' => 'New Caledonia', 'dial_code' => '687 ', 'iso2' => 'NC', 'iso3' => 'NCL',],
            ['name' => 'New Zealand', 'dial_code' => '64', 'iso2' => 'NZ', 'iso3' => 'NZL',],
            ['name' => 'Nicaragua', 'dial_code' => '505 ', 'iso2' => 'NI', 'iso3' => 'NIC',],
            ['name' => 'Niger', 'dial_code' => '227 ', 'iso2' => 'NE', 'iso3' => 'NER',],
            ['name' => 'Nigeria', 'dial_code' => '234 ', 'iso2' => 'NG', 'iso3' => 'NGA',],
            ['name' => 'Niue ', 'dial_code' => '683 ', 'iso2' => 'NU', 'iso3' => 'NIU',],
            ['name' => 'North Korea', 'dial_code' => '850 ', 'iso2' => 'KP', 'iso3' => 'PRK',],
            ['name' => 'Northern Mariana Islands ', 'dial_code' => '1-670 ', 'iso2' => 'MP', 'iso3' => 'MNP',],
            ['name' => 'Norway ', 'dial_code' => '47', 'iso2' => 'NO', 'iso3' => 'NOR',],
            ['name' => 'Oman ', 'dial_code' => '968 ', 'iso2' => 'OM', 'iso3' => 'OMN',],
            ['name' => 'Pakistan ', 'dial_code' => '92', 'iso2' => 'PK', 'iso3' => 'PAK',],
            ['name' => 'Palau', 'dial_code' => '680 ', 'iso2' => 'PW', 'iso3' => 'PLW',],
            ['name' => 'Palestine', 'dial_code' => '970 ', 'iso2' => 'PS', 'iso3' => 'PSE',],
            ['name' => 'Panama ', 'dial_code' => '507 ', 'iso2' => 'PA', 'iso3' => 'PAN',],
            ['name' => 'Papua New Guinea ', 'dial_code' => '675 ', 'iso2' => 'PG', 'iso3' => 'PNG',],
            ['name' => 'Paraguay ', 'dial_code' => '595 ', 'iso2' => 'PY', 'iso3' => 'PRY',],
            ['name' => 'Peru ', 'dial_code' => '51', 'iso2' => 'PE', 'iso3' => 'PER',],
            ['name' => 'Philippines', 'dial_code' => '63', 'iso2' => 'PH', 'iso3' => 'PHL',],
            ['name' => 'Pitcairn ', 'dial_code' => '64', 'iso2' => 'PN', 'iso3' => 'PCN',],
            ['name' => 'Poland ', 'dial_code' => '48', 'iso2' => 'PL', 'iso3' => 'POL',],
            ['name' => 'Portugal ', 'dial_code' => '351 ', 'iso2' => 'PT', 'iso3' => 'PRT',],
            ['name' => 'Puerto Rico', 'dial_code' => '1-787, 1-939', 'iso2' => 'PR', 'iso3' => 'PRI',],
            ['name' => 'Qatar', 'dial_code' => '974 ', 'iso2' => 'QA', 'iso3' => 'QAT',],
            ['name' => 'Republic of the Congo', 'dial_code' => '242 ', 'iso2' => 'CG', 'iso3' => 'COG',],
            ['name' => 'Reunion', 'dial_code' => '262 ', 'iso2' => 'RE', 'iso3' => 'REU',],
            ['name' => 'Romania', 'dial_code' => '40', 'iso2' => 'RO', 'iso3' => 'ROU',],
            ['name' => 'Russia ', 'dial_code' => '7 ', 'iso2' => 'RU', 'iso3' => 'RUS',],
            ['name' => 'Rwanda ', 'dial_code' => '250 ', 'iso2' => 'RW', 'iso3' => 'RWA',],
            ['name' => 'Saint Barthelemy ', 'dial_code' => '590 ', 'iso2' => 'BL', 'iso3' => 'BLM',],
            ['name' => 'Saint Helena ', 'dial_code' => '290 ', 'iso2' => 'SH', 'iso3' => 'SHN',],
            ['name' => 'Saint Kitts and Nevis', 'dial_code' => '1-869 ', 'iso2' => 'KN', 'iso3' => 'KNA',],
            ['name' => 'Saint Lucia', 'dial_code' => '1-758 ', 'iso2' => 'LC', 'iso3' => 'LCA',],
            ['name' => 'Saint Martin ', 'dial_code' => '590 ', 'iso2' => 'MF', 'iso3' => 'MAF',],
            ['name' => 'Saint Pierre and Miquelon', 'dial_code' => '508 ', 'iso2' => 'PM', 'iso3' => 'SPM',],
            ['name' => 'Saint Vincent and the Grenadines ', 'dial_code' => '1-784 ', 'iso2' => 'VC', 'iso3' => 'VCT',],
            ['name' => 'Samoa', 'dial_code' => '685 ', 'iso2' => 'WS', 'iso3' => 'WSM',],
            ['name' => 'San Marino ', 'dial_code' => '378 ', 'iso2' => 'SM', 'iso3' => 'SMR',],
            ['name' => 'Sao Tome and Principe', 'dial_code' => '239 ', 'iso2' => 'ST', 'iso3' => 'STP',],
            ['name' => 'Saudi Arabia ', 'dial_code' => '966 ', 'iso2' => 'SA', 'iso3' => 'SAU',],
            ['name' => 'Senegal', 'dial_code' => '221 ', 'iso2' => 'SN', 'iso3' => 'SEN',],
            ['name' => 'Serbia ', 'dial_code' => '381 ', 'iso2' => 'RS', 'iso3' => 'SRB',],
            ['name' => 'Seychelles ', 'dial_code' => '248 ', 'iso2' => 'SC', 'iso3' => 'SYC',],
            ['name' => 'Sierra Leone ', 'dial_code' => '232 ', 'iso2' => 'SL', 'iso3' => 'SLE',],
            ['name' => 'Singapore', 'dial_code' => '65', 'iso2' => 'SG', 'iso3' => 'SGP',],
            ['name' => 'Sint Maarten ', 'dial_code' => '1-721 ', 'iso2' => 'SX', 'iso3' => 'SXM',],
            ['name' => 'Slovakia ', 'dial_code' => '421 ', 'iso2' => 'SK', 'iso3' => 'SVK',],
            ['name' => 'Slovenia ', 'dial_code' => '386 ', 'iso2' => 'SI', 'iso3' => 'SVN',],
            ['name' => 'Solomon Islands', 'dial_code' => '677 ', 'iso2' => 'SB', 'iso3' => 'SLB',],
            ['name' => 'Somalia', 'dial_code' => '252 ', 'iso2' => 'SO', 'iso3' => 'SOM',],
            ['name' => 'South Africa ', 'dial_code' => '27', 'iso2' => 'ZA', 'iso3' => 'ZAF',],
            ['name' => 'South Korea', 'dial_code' => '82', 'iso2' => 'KR', 'iso3' => 'KOR',],
            ['name' => 'South Sudan', 'dial_code' => '211 ', 'iso2' => 'SS', 'iso3' => 'SSD',],
            ['name' => 'Spain', 'dial_code' => '34', 'iso2' => 'ES', 'iso3' => 'ESP',],
            ['name' => 'Sri Lanka', 'dial_code' => '94', 'iso2' => 'LK', 'iso3' => 'LKA',],
            ['name' => 'Sudan', 'dial_code' => '249 ', 'iso2' => 'SD', 'iso3' => 'SDN',],
            ['name' => 'Suriname ', 'dial_code' => '597 ', 'iso2' => 'SR', 'iso3' => 'SUR',],
            ['name' => 'Svalbard and Jan Mayen ', 'dial_code' => '47', 'iso2' => 'SJ', 'iso3' => 'SJM',],
            ['name' => 'Swaziland', 'dial_code' => '268 ', 'iso2' => 'SZ', 'iso3' => 'SWZ',],
            ['name' => 'Sweden ', 'dial_code' => '46', 'iso2' => 'SE', 'iso3' => 'SWE',],
            ['name' => 'Switzerland', 'dial_code' => '41', 'iso2' => 'CH', 'iso3' => 'CHE',],
            ['name' => 'Syria', 'dial_code' => '963 ', 'iso2' => 'SY', 'iso3' => 'SYR',],
            ['name' => 'Taiwan ', 'dial_code' => '886 ', 'iso2' => 'TW', 'iso3' => 'TWN',],
            ['name' => 'Tajikistan ', 'dial_code' => '992 ', 'iso2' => 'TJ', 'iso3' => 'TJK',],
            ['name' => 'Tanzania ', 'dial_code' => '255 ', 'iso2' => 'TZ', 'iso3' => 'TZA',],
            ['name' => 'Thailand ', 'dial_code' => '66', 'iso2' => 'TH', 'iso3' => 'THA',],
            ['name' => 'Togo ', 'dial_code' => '228 ', 'iso2' => 'TG', 'iso3' => 'TGO',],
            ['name' => 'Tokelau', 'dial_code' => '690 ', 'iso2' => 'TK', 'iso3' => 'TKL',],
            ['name' => 'Tonga', 'dial_code' => '676 ', 'iso2' => 'TO', 'iso3' => 'TON',],
            ['name' => 'Trinidad and Tobago', 'dial_code' => '1-868 ', 'iso2' => 'TT', 'iso3' => 'TTO',],
            ['name' => 'Tunisia', 'dial_code' => '216 ', 'iso2' => 'TN', 'iso3' => 'TUN',],
            ['name' => 'Turkey ', 'dial_code' => '90', 'iso2' => 'TR', 'iso3' => 'TUR',],
            ['name' => 'Turkmenistan ', 'dial_code' => '993 ', 'iso2' => 'TM', 'iso3' => 'TKM',],
            ['name' => 'Turks and Caicos Islands ', 'dial_code' => '1-649 ', 'iso2' => 'TC', 'iso3' => 'TCA',],
            ['name' => 'Tuvalu ', 'dial_code' => '688 ', 'iso2' => 'TV', 'iso3' => 'TUV',],
            ['name' => 'U.S. Virgin Islands', 'dial_code' => '1-340 ', 'iso2' => 'VI', 'iso3' => 'VIR',],
            ['name' => 'Uganda ', 'dial_code' => '256 ', 'iso2' => 'UG', 'iso3' => 'UGA',],
            ['name' => 'Ukraine', 'dial_code' => '380 ', 'iso2' => 'UA', 'iso3' => 'UKR',],
            ['name' => 'United Arab Emirates ', 'dial_code' => '971 ', 'iso2' => 'AE', 'iso3' => 'ARE',],
            ['name' => 'United Kingdom ', 'dial_code' => '44', 'iso2' => 'GB', 'iso3' => 'GBR',],
            ['name' => 'United States', 'dial_code' => '1 ', 'iso2' => 'US', 'iso3' => 'USA',],
            ['name' => 'Uruguay', 'dial_code' => '598 ', 'iso2' => 'UY', 'iso3' => 'URY',],
            ['name' => 'Uzbekistan ', 'dial_code' => '998 ', 'iso2' => 'UZ', 'iso3' => 'UZB',],
            ['name' => 'Vanuatu', 'dial_code' => '678 ', 'iso2' => 'VU', 'iso3' => 'VUT',],
            ['name' => 'Vatican', 'dial_code' => '379 ', 'iso2' => 'VA', 'iso3' => 'VAT',],
            ['name' => 'Venezuela', 'dial_code' => '58', 'iso2' => 'VE', 'iso3' => 'VEN',],
            ['name' => 'Vietnam', 'dial_code' => '84', 'iso2' => 'VN', 'iso3' => 'VNM',],
            ['name' => 'Wallis and Futuna', 'dial_code' => '681 ', 'iso2' => 'WF', 'iso3' => 'WLF',],
            ['name' => 'Western Sahara ', 'dial_code' => '212 ', 'iso2' => 'EH', 'iso3' => 'ESH',],
            ['name' => 'Yemen', 'dial_code' => '967 ', 'iso2' => 'YE', 'iso3' => 'YEM',],
            ['name' => 'Zambia ', 'dial_code' => '260 ', 'iso2' => 'ZM', 'iso3' => 'ZMB',],
            ['name' => 'Zimbabwe ', 'dial_code' => '263 ', 'iso2' => 'ZW', 'iso3' => 'ZWE',],
        ];

        foreach($seedCountries as $country){
            Country::create($country);
        }
    }
}


